cse230hw4: main.o util.o link_info.o imap.o visit.o date.o ip_address.o barchart.o
	g++ -o cse230hw4 main.o util.o link_info.o imap.o visit.o date.o ip_address.o barchart.o
main.o: main.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c main.cpp
util.o: util.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c util.cpp
link_info.o: link_info.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c link_info.cpp
imap.o: imap.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c imap.cpp
visit.o: visit.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c visit.cpp
date.o: date.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c date.cpp
ip_address.o: ip_address.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c ip_address.cpp
barchart.o: barchart.cpp common.h util.h link_info.h imap.h visit.h date.h ip_address.h barchart.h
	g++ -c barchart.cpp